### ISSUE TITLE
Need to Add Reader for Platform Level for granting access at the skill level

### ISSUE THREAD

**Issue by miltatibm** [ibm-cloud-docs/assistant#411]
This part https://cloud.ibm.com/docs/assistant?topic=assistant-access-control#access-control-common-roles for giving access at the skill level you also need Reader at the platform level per this gh
https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/49763#issuecomment-36593633 Both Viewer and Reader are needed

**Comment by crlordan** [comment]
In our draft environment, the **Common Roles** table has been updated with Viewer, Reader for the rows about skill access:

https://test.cloud.ibm.com/docs/assistant?topic=assistant-access-control#access-control-common-roles

Please review and make sure this is the right update, and/or suggest what else needs to be changed? Because the original GitHub issue 49763 isn't very easy to follow.

**Comment by miltatibm** [comment]
@crlordan looks good! Thank you!!

**Comment by miltatibm** [comment]
@crlordan when will the change be in the public documentation? TIA

**Comment by crlordan** [comment]
Sorry about that. The customer-facing documentation is now updated: https://cloud.ibm.com/docs/assistant?topic=assistant-access-control#access-control-common-roles
