### ISSUE TITLE
How to use Date picker within IBM Watson Assistant?

### ISSUE THREAD

**Issue by aymalkhalid** [ibm-cloud-docs/assistant#420]
How to use a Date picker to collect a Date from customer response. As mentioned in the [Relase 6.4.0](https://cloud.ibm.com/docs/assistant?topic=assistant-release-notes-chat#6.4.0).. I can not find it in the response type also searched a lot on the internet but no help is available.
![image](https://user-images.githubusercontent.com/32593370/164996978-1799e085-d26f-42d3-80f1-927d90d17961.png)

**Comment by robert-berry** [comment]
You do not have to do anything to enable the date picker. For any action step in which you select a **Date** customer response, the `date` response type is automatically sent, and the web chat integration displays the date picker. If you have an existing step that you created before the introduction of the date picker, you need to delete the customer response and re-add it in order to pick up this new behavior.
